In [1]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

Using TensorFlow backend.


In [2]:
model = Sequential()
model.add(Dense(1, input_dim=6, activation='relu'))
model.add(Dense(5, activation='softmax'))

In [3]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [4]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 7         
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 10        
Total params: 17
Trainable params: 17
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit()
# Not supposed to run model because, for now we are filling weights randomly

In [ ]:
#np.random.rand(18)

In [6]:
weights = [np.random.rand(*w.shape) for w in model.get_weights()]

# update
model.set_weights(weights)

In [8]:
for layer in model.layers:
    weights = layer.get_weights() # list of numpy arrays

In [9]:
weights = model.get_weights()
weights
#Here you can see randomized weights filled

[array([[0.46623972],
        [0.2432728 ],
        [0.5263947 ],
        [0.6143005 ],
        [0.6665657 ],
        [0.35109395]], dtype=float32),
 array([0.11996169], dtype=float32),
 array([[0.74564344, 0.87471837, 0.00663298, 0.18827769, 0.62516487]],
       dtype=float32),
 array([0.11882559, 0.63776696, 0.77743006, 0.7974116 , 0.28238386],
       dtype=float32)]

In [ ]:
#print(weights)

In [12]:
def disease(a):
  if (a ==0):return "Pepper__bell___Bacterial_spot"
  if (a ==1):return "Pepper__bell___healthy"
  if (a ==2):return "Potato___Early_blight"
  if (a ==3):return "Potato___healthy"
  if (a ==4):return "Potato___Late_blight"
  if (a ==5):return "Tomato__Target_Spot"
  if (a ==6):return "Tomato__Tomato_mosaic_virus"
  if (a ==7):return "Tomato__Tomato_YellowLeaf__Curl_Virus"
  if (a ==8):return "Tomato_Bacterial_spot"
  if (a ==8):return "Tomato_Early_blight"
  if (a ==8):return "Tomato_healthy"
  if (a ==8):return "Tomato_Late_blight"
  if (a ==8):return "Tomato_Leaf_Mold"
  if (a ==8):return "Tomato_Septoria_leaf_spot"
  if (a ==8):return "Tomato_Spider_mites_Two_spotted_spider_mite"    

  #for now instance we are just searching disease in pepper and potato
  #Other catagories can easily be detected by changing model architecture


In [13]:
Xnew = np.array([np.random.rand(6)])   #here we will fetch data from api of pollution
#
# make a prediction
ynew = model.predict_classes(Xnew)
#ynew = model.predict(Xnew)
# show the inputs and predicted outputs
higest=np.where(ynew[0] == ynew[0].max())
higest
#print("X=%s, Predicted=%s" % (Xnew[0], disease(higest[0][0])))
print(" Predicted Disease = %s" % ( disease(higest[0][0])))

 Predicted Disease = Pepper__bell___Bacterial_spot


In [ ]:
#This disease Detected is according to Updated model architecture
#This includes searching of disease in perticular catagory, i.e. Pepper, Potato